{
 "title": "Oracle VPN Status",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Network Traffic (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(v2ray_traffic_downlink_bytes_total{dimension=\"inbound\"}[2m])) * 8 / 1000000",
     "legendFormat": "{{Download}}"
    },
    {
     "expr": "sum(rate(v2ray_traffic_uplink_bytes_total{dimension=\"inbound\"}[2m])) * 8 / 1000000",
     "legendFormat": "{{Upload}}"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{Ram Used}}"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Per User",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "v2ray_traffic_uplink_bytes_total{dimension=\"user\"} + v2ray_traffic_downlink_bytes_total{dimension=\"user\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}